"""
Unit and integration tests for Sub-Phase 3.1:
- 3.1.A: Waveform Acoustic Confidence Heatmap (telemetry fields & validation)
- 3.1.B: FFT Spectrogram Waterfall Display (generation, caching, and API endpoint)
- 3.1.C: Multi-Speaker Timeline Gantt Ribbon
"""

import io
import tempfile
from pathlib import Path
import numpy as np
import soundfile as sf
import torch
from PIL import Image
from fastapi.testclient import TestClient

from transcript_suite.audio.spectrogram import generate_spectrogram_image
from transcript_suite.web.app import app, TASKS


def _create_dummy_wav(duration_sec: float = 2.0, sr: int = 16000) -> str:
    """Helper to generate a clean synthetic audio file with voice-like harmonic tones."""
    t = np.linspace(0, duration_sec, int(sr * duration_sec), endpoint=False, dtype=np.float32)
    # Fundamental frequency at 220 Hz + formants at 440 Hz and 1200 Hz
    signal = 0.4 * np.sin(2 * np.pi * 220 * t) + 0.3 * np.sin(2 * np.pi * 440 * t) + 0.2 * np.sin(2 * np.pi * 1200 * t)
    
    tmp = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
    sf.write(tmp.name, signal, sr)
    tmp.close()
    return tmp.name


def test_spectrogram_generation_valid_audio():
    """3.1.B: Verify Mel-Spectrogram generation, PNG encoding, dimensions, and caching."""
    wav_path = _create_dummy_wav(duration_sec=1.5, sr=16000)
    cache_path = Path(f"{wav_path}.spec_600x64.png")

    try:
        # First call: generates fresh spectrogram
        png_bytes = generate_spectrogram_image(wav_path, width=600, height=64)
        assert png_bytes.startswith(b"\x89PNG\r\n\x1a\n"), "Spectrogram must start with valid PNG signature"
        
        # Verify image properties
        img = Image.open(io.BytesIO(png_bytes))
        assert img.size == (600, 64), f"Expected (600, 64), got {img.size}"
        assert img.format == "PNG"

        # Verify cache file was written to disk
        assert cache_path.exists(), "Cache file must exist after generation"
        assert cache_path.stat().st_size == len(png_bytes)

        # Second call: must hit cache
        cached_bytes = generate_spectrogram_image(wav_path, width=600, height=64)
        assert cached_bytes == png_bytes, "Cached bytes must match generated bytes"

    finally:
        if Path(wav_path).exists():
            Path(wav_path).unlink()
        if cache_path.exists():
            cache_path.unlink()


def test_spectrogram_generation_fallback_missing_file():
    """3.1.B: Verify graceful fallback image generation when audio file does not exist."""
    missing_path = "/non/existent/path/audio.wav"
    png_bytes = generate_spectrogram_image(missing_path, width=400, height=48)
    assert png_bytes.startswith(b"\x89PNG\r\n\x1a\n")

    img = Image.open(io.BytesIO(png_bytes))
    assert img.size == (400, 48)
    assert img.format == "PNG"


def test_spectrogram_api_endpoints():
    """3.1.B: Verify FastAPI GET /api/audio/{task_id}/spectrogram endpoint."""
    client = TestClient(app)

    # 1. 404 for invalid task
    res_404 = client.get("/api/audio/unknown-task-id-9999/spectrogram")
    assert res_404.status_code == 404

    # 2. Register mock task
    wav_orig = _create_dummy_wav(duration_sec=1.0)
    wav_proc = _create_dummy_wav(duration_sec=1.0)
    task_id = "test-visual-telemetry-task"

    TASKS[task_id] = {
        "id": task_id,
        "file_path": wav_orig,
        "processed_audio": wav_proc,
        "status": "completed",
        "segments": [
            {
                "start": 0.0,
                "end": 0.5,
                "text": "Speaker zero speaking",
                "speaker": "Speaker 0",
                "consensus_score": 0.95,
                "snr_db": 22.4,
                "loop_circuit_breaker_tripped": False
            },
            {
                "start": 0.5,
                "end": 1.0,
                "text": "Speaker one answering",
                "speaker": "Speaker 1",
                "consensus_score": 0.60,
                "snr_db": 14.1,
                "loop_circuit_breaker_tripped": True
            }
        ]
    }

    try:
        # Test original audio spectrogram
        res_orig = client.get(f"/api/audio/{task_id}/spectrogram?processed=false&width=700&height=50")
        assert res_orig.status_code == 200
        assert res_orig.headers["content-type"] == "image/png"
        img_orig = Image.open(io.BytesIO(res_orig.content))
        assert img_orig.size == (700, 50)

        # Test processed audio spectrogram
        res_proc = client.get(f"/api/audio/{task_id}/spectrogram?processed=true&width=500&height=40")
        assert res_proc.status_code == 200
        assert res_proc.headers["content-type"] == "image/png"
        img_proc = Image.open(io.BytesIO(res_proc.content))
        assert img_proc.size == (500, 40)

        # Test fallback when processed_audio is None
        TASKS[task_id]["processed_audio"] = None
        res_fallback = client.get(f"/api/audio/{task_id}/spectrogram?processed=true&width=400&height=32")
        assert res_fallback.status_code == 200
        assert res_fallback.headers["content-type"] == "image/png"

    finally:
        if task_id in TASKS:
            del TASKS[task_id]
        if Path(wav_orig).exists():
            Path(wav_orig).unlink()
        if Path(wav_proc).exists():
            Path(wav_proc).unlink()
        for p in Path("/tmp").glob("*.spec_*.png"):
            try:
                p.unlink()
            except OSError:
                pass
